### ISSUE TITLE
Provide AppleScript source

### ISSUE THREAD

**Issue by gianpaj** [jjahr/ffmpeg-droplet#3]
Hi, thanks for this scripts. As far as I know the uploaded .app files as compiled or binary scripts.
Could you please upload the source files so we would extend or modify them?

For example Instagram now supports 60 second videos

thanks

**Comment by jjahr** [comment]
I'm pretty sure the .app contains source code as well as compiled code.  My workflow is to open the .app in Script Editor on OSX, edit the code, then when I save it recompiles into an executable .app.  I hope that works for you.

**Comment by gianpaj** [comment]
I found how to do it. You have rename the `.app` files to `.scpt`.
